---
- hosts: all
  become: true
  pre_tasks:
    - name: install apache2 and tuned pacakage
      tags: always
      yum:
        name:
          - "{{apache_package_name}}"
          - tuned
          - nfs-utils
        state: latest
        update_cache: yes


- hosts: all
  become: true
  roles:
    - base


- hosts: main_server
  become: true
  roles:
    - mass

- hosts: slave_server
  become: yes
  roles:
    - workstation
